import { Photo } from './photo';
export interface IUser {
  Id: number;
  UserLoginName: string;
  GoogleLoginName: string;
  FbLoginName: string;
  LoginType: string;
  Password: string;
  Name: string;
  Email: string;
  Mobile: string;
  Dob: string;
  Profession: string;
  Gender: string;
  Language: string;
  Location: string;
  Country: string;
  Summary: string;
  PreferredBankNo: string;
  PreferredBankName: string;
  PreferredAccNo: string;
  PreferredAccName: string;
  Designation: string;
  CompanyName: string;
  CompanyNature: string;
  CompanyNo: string;
  CompanyLocation: string;
  FailedLoginAttemp: number;
  IsLoggedOut: number;
  IsTempBlocked: number;
  IsActive: number;
  lastFailedLogin: Date;
  lastSuccessfullLogin: Date;
  sessionKey: string;
  UserTypeId: number;
  AccountTypeId: number;
  isFeatureUnlockedInfluencer: number;
  PhotoId: number;
  CreatedBy: string;
  CreatedDate: Date;
  UserPhoto: any;
  UserTag: string[];
};

export class User implements IUser {
  Id: number;
  UserLoginName: string;
  GoogleLoginName: string;
  FbLoginName: string;
  LoginType: string;
  Password: string;
  Name: string;
  Email: string;
  Mobile: string;
  Dob: string;
  Profession: string;
  Gender: string;
  Language: string;
  Location: string;
  Country: string;
  Summary: string;
  PreferredBankNo: string;
  PreferredBankName: string;
  PreferredAccNo: string;
  PreferredAccName: string;
  Designation: string;
  CompanyName: string;
  CompanyNature: string;
  CompanyNo: string;
  CompanyLocation: string;
  FailedLoginAttemp: number;
  IsLoggedOut: number;
  IsTempBlocked: number;
  IsActive: number;
  lastFailedLogin: Date;
  lastSuccessfullLogin: Date;
  sessionKey: string;
  UserTypeId: number;
  AccountTypeId: number;
  isFeatureUnlockedInfluencer: number;
  PhotoId: number;
  CreatedBy: string;
  CreatedDate: Date;
  UserPhoto: any;
  UserTag: string[];

  constructor(user?: any) {
    this.Id = user && user.Id || null;
  }
};
